function Table_Req = IsGmxTableRequired(Settings)
if ~isfield(Settings,'GaussianCharge')
    Settings.GaussianCharge = false;
end
if ~isfield(Settings,'Polarization')
    Settings.Polarization = false;
end
if strncmp(Settings.Theory,'JC',2)
    Table_Req = Settings.GaussianCharge || Settings.Polarization || ...
        (Settings.S.D.All <= 0) || (Settings.S.R.All <= 0) ...
        || (Settings.S.D.MM <= 0) || (Settings.S.R.MM <= 0) ...
        || (Settings.S.D.XX <= 0) || (Settings.S.R.XX <= 0) ...
        || (Settings.S.D.MX <= 0) || (Settings.S.R.MX <= 0) ...
        || (Settings.S.E.MM <= 0) || (Settings.S.S.MM <= 0) ...
        || (Settings.S.E.XX <= 0) || (Settings.S.S.XX <= 0) ...
        || (Settings.S.E.MX <= 0) || (Settings.S.S.MX <= 0) ...
        || (Settings.CR_Damp.MX.r_d > 0 && Settings.CR_Damp.MX.b > 0) ...
        || (Settings.CR_Damp.MM.r_d > 0 && Settings.CR_Damp.MM.b > 0) ...
        || (Settings.CR_Damp.XX.r_d > 0 && Settings.CR_Damp.XX.b > 0) ...
        || Settings.C6_Damp.MX ~= 0 || Settings.C6_Damp.MM ~= 0 || Settings.C6_Damp.XX ~= 0 ...
        || Settings.GAdjust_MX(1,1) ~= 0 || Settings.GAdjust_MM(1,1) ~= 0 || Settings.GAdjust_XX(1,1) ~= 0 ...
        || Settings.S.N.MM.Value >= 0 || Settings.S.N.XX.Value >= 0 || Settings.S.N.MX.Value >= 0;
else
    Table_Req = true;
end
    
end