% Script to run any post-processing to MD simulations
function MD_Postprocessor(Settings)

if ~isstruct(Settings)
    Settings = load(Settings,'-mat').Settings;
end

py.LiXStructureDetector.Check_Structures(Settings.WorkDir, Settings.Salt,...
            pyargs('SystemName',Settings.JobName,...
            'FileType',Settings.CoordType,...
            'SavePredictionsImage',Settings.SavePredictionsImage,...
            'ML_TimeLength',Settings.ML_TimeLength,...
            'ML_TimeStep',Settings.ML_TimeStep,...
            'TimePerFrame',Settings.TimePerFrame,...
            'SaveTrajectory',Settings.SaveTrajectory,...
            'SaveFeatures', Settings.SaveFeatures,...
            'SavePredictions',Settings.SavePredictions,...
            'Qlm_Average',Settings.Qlm_Average,...
            'Voronoi',Settings.Voronoi));

fclose(fopen(fullfile(Settings.WorkDir,'POSTPROCESS_COMPLETE'), 'w'));
end