function CellOpt_text = Cell_Optimization_Text(opt_type,opt_conv,max_cycle,...
    NUMGRCEL,TOLDEG,TOLDEX,EXTPRESS,Internal_Coordinates,Updating_Scheme)

if Internal_Coordinates && ~strcmpi(opt_type,'CELLONLY')
    IC_Text = [newline 'INTREDUN'];
else
    IC_Text = '';
end


if NUMGRCEL
    CellOpt_text = ['OPTGEOM' newline ...
        opt_type IC_Text newline ...
        Updating_Scheme newline ...
        'TOLDEE' newline ...
        num2str(opt_conv) newline ...
        'MAXCYCLE' newline ....
        num2str(max_cycle) newline ...
        'NUMGRCEL' newline ...
        'ONELOG' newline ...
        'PRINTFORCES' newline ...
        'PRINTOPT' newline ...
        'TOLDEG' newline ...
        num2str(TOLDEG) newline ...
        'TOLDEX' newline ...
        num2str(TOLDEX) newline ...
        EXTPRESS ...
        'END[OPTG]'];
else
    CellOpt_text = ['OPTGEOM' newline ...
        opt_type IC_Text newline ...
        Updating_Scheme newline ...
        'TOLDEE' newline ...
        num2str(opt_conv) newline ...
        'MAXCYCLE' newline ....
        num2str(max_cycle) newline ...
        'ONELOG' newline ...
        'PRINTFORCES' newline ...
        'PRINTOPT' newline ...
        'TOLDEG' newline ...
        num2str(TOLDEG) newline ...
        'TOLDEX' newline ...
        num2str(TOLDEX) newline ...
        EXTPRESS ...
        'END[OPTG]'];
end
end