function Vib_Input = Vibrational_Analysis_Text(QHA,QHA_Step,QHA_Points,QHA_VRANGE,T,P,Phonon_Dispersion,Supercell,PDOS,PDOS_Range,PDOS_projected,Opttext)

Supercell_txt = [ num2str(Supercell) ' 0 0' newline ...
                '0 ' num2str(Supercell) ' 0' newline ...
                '0 0 ' num2str(Supercell)];

if PDOS && ~QHA
    PDOS_text = ['PDOS' newline ...
        num2str(PDOS_Range(1)) ' ' num2str(PDOS_Range(2)) newline ...
        num2str(PDOS_projected) newline];
else
    PDOS_text = '';
end

if ~isempty(QHA_VRANGE)
    QHA_Range = ['RANGE' newline ...
        num2str(QHA_VRANGE(1)) ' ' num2str(QHA_VRANGE(2)) ' ' num2str(QHA_VRANGE(3))];
else
    QHA_Range = ['STEP' newline ...
            num2str(QHA_Step) newline ...
            'POINTS' newline ...
            num2str(QHA_Points)];
end

if isempty(Opttext)
    if QHA
        Vib_Input = ['SCELPHONO' newline ...
            Supercell_txt newline ...
            'QHA' newline ...
            'TEMPERAT' newline ...
            T newline ...
            QHA_Range newline ...
            'END[QuasiHarmonicApprox]' newline];
    elseif Phonon_Dispersion
        Vib_Input = ['SCELPHONO' newline ...
            Supercell_txt newline ...
            'FREQCALC' newline ...
            'DISPERSION' newline ...
            'PRESSURE' newline ...
            P newline ...
            'TEMPERAT' newline ...
            T newline ...
            PDOS_text ...
            'END[FREQ]' newline];
    else
        Vib_Input = ['FREQCALC' newline ...
            'PRESSURE' newline ...
            P newline ...
            'TEMPERAT' newline ...
            T newline ...
            PDOS_text ...
            'END[FREQ]' newline];
    end
else
    if QHA
        Vib_Input = ['SCELPHONO' newline ...
            Supercell_txt newline ...
            'QHA' newline ...
            'TEMPERAT' newline ...
            T newline ...
            QHA_Range newline ...
            'PRE' Opttext newline ...
            'END[QHA]' newline];
    elseif Phonon_Dispersion
        Vib_Input = ['SCELPHONO' newline ...
            Supercell_txt newline ...
            'FREQCALC' newline ...
            'DISPERSION' newline ...
            'PRESSURE' newline ...
            P newline ...
            'TEMPERAT' newline ...
            T newline ...
            PDOS_text ...
            'PRE' Opttext newline ...
            'END[FREQ]' newline];
    else
        Vib_Input = ['FREQCALC' newline ...
            'PRESSURE' newline ...
            P newline ...
            'TEMPERAT' newline ...
            T newline ...
            PDOS_text ...
            'PRE' Opttext newline ...
            'END[FREQ]' newline];
    end
end
end