function Opt_out = cp2k_opt_geom

Opt_out=   ['  &GEO_OPT' newline ...
            '	TYPE MINIMIZATION' newline ...
            '	OPTIMIZER BFGS' newline ...
            '	MAX_ITER 100' newline ...
            '	MAX_DR 1.8000E-04' newline ...
            '	MAX_FORCE 4.5000E-05' newline ...
            '	RMS_DR 1.2000E-04' newline ...
            '	RMS_FORCE 3.0000E-05' newline ...
            '	&PRINT' newline ...
            '		&PROGRAM_RUN_INFO MEDIUM' newline ...
            '		&END PROGRAM_RUN_INFO' newline ...
            '	&END PRINT' newline ...
            '  &END GEO_OPT'];
end