function Rel_out = cp2k_relativistic(Rel)
    if strcmp(Rel.Method,'DKH') % DKH METHOD
        
        Rel_out=   ['	&RELATIVISTIC' newline ...
                    '		DKH_ORDER ' num2str(Rel.DKH_Order) newline ...
                    '		METHOD DKH' newline ...
                    '		POTENTIAL ' Rel.Potential newline ...
                    '		TRANSFORMATION ' Rel.Transformation newline ...
                    '		Z_CUTOFF ' num2str(Rel.Z_Cutoff) newline ...
                    '	&END RELATIVISTIC'];

    else % ZORA METHOD

        Rel_out=   ['	&RELATIVISTIC' newline ...
                    '		METHOD ZORA' newline ...
                    '		ZORA_TYPE ' Rel.ZORA_Type newline ...
                    '		Z_CUTOFF ' num2str(Rel.Z_Cutoff) newline ...
                    '	&END RELATIVISTIC'];
    end
end