function [Models,Dependent_var,Legend_txt,x_label,xlimits,x_ticks,Parameters] =  MP_Set_Info(Set)
% some default settings
Parameters.ScaleCompressibility = '$\beta_{T} = 1\beta_{T}^{\circ}$';
Parameters.PreEquilibrate = 'Pre-Equilibration OFF';

switch Set
    case 'Set1' % Set1: varying XY with fixed Z=10 nm, tmax = 1 ns with $\Delta x_{\mathrm{liquid}}$ = 0.15
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 1$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 15 \%';
        Parameters.XYZ = '';
        Parameters.XY = '';
        Parameters.Z = '$z = 10$ nm';
        Parameters.N = '';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC' 'TF'};
        Dependent_var = 'a_vec_sol';
        Legend_txt = 'Melting Point vs (X,Y): Z = 10 nm, $t_{max}$ = 1 ns, $\Delta x_{\mathrm{liquid}}$ = 15 \%';
        x_label = 'Box Length X and Y [nm]';
        xlimits = [2 16];
        x_ticks = 2:2:16;
    case 'Set2' % Set2: varying Z with fixed XY = 6 nm, tmax = 1 ns with $\Delta x_{\mathrm{liquid}}$ = 0.15
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 1$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 15 \%';
        Parameters.XYZ = '';
        Parameters.XY = '(x,y) = 6 nm';
        Parameters.Z = '';
        Parameters.N = '';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC' 'TF'};
        Dependent_var = 'c_vec_tot'; %'c_vec_tot'; %'Liq_L'; 'N_Total'
        Legend_txt = 'Melting Point vs Z: (X,Y) = 6 nm, $t_{max}$ = 1 ns, $\Delta x_{\mathrm{liquid}}$ = 15 \%';
        x_label = 'Box Height Z [nm]';
        xlimits = [2 16];
        x_ticks = 2:2:16;
    case 'Set3' % Set3: droplet with varying R, tmax = 1 ns with $\Delta x_{\mathrm{liquid}}$ = 0.15
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 1$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 15 \%';
        Parameters.XYZ = '';
        Parameters.XY = '';
        Parameters.Z = '';
        Parameters.N = '';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC' 'TF'};
        Dependent_var = 'Solid_R'; %'Solid_R';
        Legend_txt = 'Melting Point vs Drop Radius: Spherical Interface, $t_{max}$ = 1 ns, $\Delta x_{\mathrm{liquid}}$ = 15 \%';
        x_label = '$R_{Solid}$ [nm]';
        xlimits = [2 8];
        x_ticks = 2:8;
    case 'Set4' % Set4: Repeated Measurements [6x6x10 nm] to check for consistency at tmax = 1 ns with $\Delta x_{\mathrm{liquid}}$ = 0.15
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 1$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 15 \%';
        Parameters.XYZ = '(x,y,z) = (6,6,10) nm';
        Parameters.XY = '(x,y) = (6,6) nm';
        Parameters.Z = 'z = 10 nm';
        Parameters.N = 'N = 11618';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'MP Reproducibility: (X,Y,Z) = (6, 6, 10) nm, N = 11618, $t_{max}$ = 1 ns, $\Delta x_{\mathrm{liquid}}$ = 15 \%';
        x_label = 'Trial Number';
        xlimits = [0 6];
        x_ticks = 1:5;
    case 'Set5' % Set5: Repeated Measurements [6x6x10 nm] to check for consistency at tmax = 2 ns with $\Delta x_{\mathrm{liquid}}$ = 0.15
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 2$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 15 \%';
        Parameters.XYZ = '(x,y,z) = (6,6,10) nm';
        Parameters.XY = '(x,y) = (6,6) nm';
        Parameters.Z = 'z = 10 nm';
        Parameters.N = 'N = 11618';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'MP Reproducibility: (X,Y,Z) = (6, 6, 10) nm, N = 11618, $t_{max}$ = 2 ns, $\Delta x_{\mathrm{liquid}}$ = 15 \%';
        x_label = 'Trial Number';
        xlimits = [0 6];
        x_ticks = 1:5;
    case 'Set6' % Set6: Repeated Measurements [8x8x10 nm] to check for consistency at tmax = 2 ns with $\Delta x_{\mathrm{liquid}}$ = 0.15
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 2$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 15 \%';
        Parameters.XYZ = '(x,y,z) = (8,8,10) nm';
        Parameters.XY = '(x,y) = (8,8) nm';
        Parameters.Z = 'z = 10 nm';
        Parameters.N = 'N = 19636';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'MP Reproducibility: (X,Y,Z) = (8, 8, 10) nm, N = 19636, $t_{max}$ = 2 ns, $\Delta x_{\mathrm{liquid}}$ = 15 \%';
        x_label = 'Trial Number';
        xlimits = [0 6];
        x_ticks = 1:5;
    case 'Set7' % Set7: Repeated Measurements [6x6x10 nm] to check for consistency at tmax = 2 ps with MeltFreezeThreshold = 0.10

        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 2$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 10 \%';
        Parameters.XYZ = '(x,y,z) = (6,6,10) nm';
        Parameters.XY = '(x,y) = (6,6) nm';
        Parameters.Z = 'z = 10 nm';
        Parameters.N = 'N = 11618';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'MP Reproducibility: (X,Y,Z) = (6, 6, 10) nm, N = 11618, $t_{max}$ = 2 ns, $\Delta x_{\mathrm{liquid}}$ = 10 \%';
        x_label = 'Trial Number';
        xlimits = [0 6];
        x_ticks = 1:5;
    case 'Set8' % Set8: Repeated Measurements [6x6x10 nm] to check for consistency at tmax = 2 ps with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 2$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6,6,10) nm';
        Parameters.XY = '(x,y) = (6,6) nm';
        Parameters.Z = 'z = 10 nm';
        Parameters.N = 'N = 11618';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'MP Reproducibility: (X,Y,Z) = (6, 6, 10) nm, N = 11618, $t_{max}$ = 2 ns, $\Delta x_{\mathrm{liquid}}$ = 25 \%';
        x_label = 'Trial Number';
        xlimits = [0 6];
        x_ticks = 1:5;
    case 'Set9' % Set9: Repeated Measurements [6x6x10 nm] to check for consistency at tmax = 5 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6,6,10) nm';
        Parameters.XY = '(x,y) = (6,6) nm';
        Parameters.Z = 'z = 10 nm';
        Parameters.N = 'N = 11618';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'MP Reproducibility: (X,Y,Z) = (6, 6, 10) nm, N = 11618, $t_{max}$ = 5 ns, $\Delta x_{\mathrm{liquid}}$ = 25 \%';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set10' % Set10: Repeated Measurements [6x6x10 nm] to check for consistency at tmax = 10 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 10$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6,6,10) nm';
        Parameters.XY = '(x,y) = (6,6) nm';
        Parameters.Z = 'z = 10 nm';
        Parameters.N = 'N = 11618';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'MP Reproducibility: (X,Y,Z) = (6, 6, 10) nm, N = 11618, $t_{max}$ = 10 ns, $\Delta x_{\mathrm{liquid}}$ = 25 \%';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set11' % Set11: Repeated Measurements [8x8x10 nm] to check for consistency at tmax = 10 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 10$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (8,8,10) nm';
        Parameters.XY = '(x,y) = (8,8) nm';
        Parameters.Z = 'z = 10 nm';
        Parameters.N = 'N = 19636';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'MP Reproducibility: (X,Y,Z) = (8, 8, 10) nm, N = 19636, $t_{max}$ = 10 ns, $\Delta x_{\mathrm{liquid}}$ = 25 \%';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set12' % Set12: Repeated Measurements [6x6x7 nm] to check for consistency at tmax = 5 ns with $\Delta x_{\mathrm{liquid}}$ = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6,6,7) nm';
        Parameters.XY = '(x,y) = (6,6) nm';
        Parameters.Z = 'z = 7 nm';
        Parameters.N = 'N = 8152';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (6, 6, 7) nm, N = 8152, $t_{max}$ = 5 ns, $\Delta x_{\mathrm{liquid}}$ = 25 \%';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set13' % Set13: Repeated Measurements [6x6x4.5 nm] to check for consistency at tmax = 5 ns with $\Delta x_{\mathrm{liquid}}$ = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6,6,4.5) nm';
        Parameters.XY = '(x,y) = (6,6) nm';
        Parameters.Z = 'z = 4.5 nm';
        Parameters.N = 'N = 5212';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (6, 6, 4.5) nm, N = 5212, $t_{max}$ = 5 ns, $\Delta x_{\mathrm{liquid}}$ = 25 \%';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set14' % Set14: Repeated Measurements 4000 atoms to check for consistency at tmax = 5 ns with $\Delta x_{\mathrm{liquid}}$ = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.41$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.5,3.5,13.9) nm';
        Parameters.XY = '(x,y) = (3.5,3.5) nm';
        Parameters.Z = 'z = 13.9 nm';
        Parameters.N = 'N = 4000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (3.5, 3.5, 13.9) nm, N = 4000, Disp Correction ON, $r_{c} = 1.41$ nm';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set15' % Set15: Repeated Measurements 2000 atoms to check for consistency at tmax = 5 ns with $\Delta x_{\mathrm{liquid}}$ = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.5,3.5,6.9) nm';
        Parameters.XY = '(x,y) = (3.5,3.5) nm';
        Parameters.Z = 'z = 6.9 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (3.5, 3.5, 6.9) nm, N = 2000, Disp Correction ON, $r_{c} = 1.4$ nm';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set16' % Set16: Repeated Measurements 1024 atoms to check for consistency at tmax = 5 ns with $\Delta x_{\mathrm{liquid}}$ = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.20$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (2.4,2.4,5.5) nm';
        Parameters.XY = '(x,y) = (2.4,2.4) nm';
        Parameters.Z = 'z = 5.5 nm';
        Parameters.N = 'N = 1024';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (2.4, 2.4, 5.5) nm, N = 1024, Disp Correction ON, $r_{c} = 1.2$ nm';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set17' % Set17: Repeated Measurements [6x6x10 nm] to check for consistency at tmax = 5 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6,6,10) nm';
        Parameters.XY = '(x,y) = (6,6) nm';
        Parameters.Z = 'z = 10 nm';
        Parameters.N = 'N = 11620';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (6, 6, 10) nm, N = 11620, Disp Correction ON, $r_{c} = 1.90$ nm';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set18' % Set18: Repeated Measurements [6x6x10 nm] to check for consistency at tmax = 5 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6,6,10) nm';
        Parameters.XY = '(x,y) = (6,6) nm';
        Parameters.Z = 'z = 10 nm';
        Parameters.N = 'N = 11620';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (6, 6, 10) nm, N = 11620, Disp Correction ON, $r_{c} = 1.90$ nm';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set19' % Set19: Repeated Measurements [6x6x14 nm] to check for consistency at tmax = 5 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6,6,14) nm';
        Parameters.XY = '(x,y) = (6,6) nm';
        Parameters.Z = 'z = 14 nm';
        Parameters.N = 'N = 16266';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (6, 6, 14) nm, N = 16266, Disp Correction OFF, $r_{c} = 1.90$ nm';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;    
    case 'Set20' % Set20: Reproducing lit value with 2000 atoms, tmax = 5 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 2.0$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 2.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'Ewald Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.5 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $2.505 \times 10^{-5}$';
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (3.0, 3.0, 6.0) nm, N = 2000, Disp Correction ON, $r_{c} = 1.40$ nm, NH Thermo, PR Baro, Ewald';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set21' % Set21: Reproducing lit value with 2000 atoms (except using PME), tmax = 5 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 2.0$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 2.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (3.0, 3.0, 6.0) nm, N = 2000, Disp Correction ON, $r_{c} = 1.40$ nm, NH Thermo, PR Baro, PME';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set22' % Set22: Reproducing lit value with 2000 atoms (except using PME + Berendsen Barostat), tmax = 5 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 2.0$ ps';
        Parameters.Barostat = 'Berendsen Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (3.0, 3.0, 6.0) nm, N = 2000, Disp Correction ON, $r_{c} = 1.40$ nm, NH Thermo, Berendsen Baro, PME';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set23' % Set23: Reproducing lit value with 2000 atoms (except using PME + V-Rescale Thermostat), tmax = 5 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 2.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (3.0, 3.0, 6.0) nm, N = 2000, Disp Correction ON, $r_{c} = 1.40$ nm, VR Thermo, PR Baro, PME';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set24' % Set24: Reproducing lit value with 2000 atoms (except using PME + Reduced Fourierspacing), tmax = 5 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 2.0$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 2.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.10 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (3.0, 3.0, 6.0) nm, N = 2000, Disp Correction ON, $r_{c} = 1.40$ nm, NH Thermo, PR Baro, PME';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set25' % Set25: Repeated Measurements [6x6x10 nm] to check for consistency at tmax = 5 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Velocity Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6,6,10) nm';
        Parameters.XY = '(x,y) = (6,6) nm';
        Parameters.Z = 'z = 10 nm';
        Parameters.N = 'N = 11618';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'MP Reproducibility: (X,Y,Z) = (6, 6, 10) nm, N = 11618, $t_{max}$ = 5 ns, $\Delta x_{\mathrm{liquid}}$ = 25 \%';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set26' % Set26: Reproducing lit value with 2000 atoms (except using PME), tmax = 5 ns with MeltFreezeThreshold = 0.25
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 2.0$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 2.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        Parameters.ScaleCompressibility = '$\beta_{T} = 5\times 10^{-2}\beta_{T}^{\circ}$';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '(X,Y,Z) = (3.0, 3.0, 6.0) nm, N = 2000, Disp Correction ON, $r_{c} = 1.40$ nm, NH Thermo, PR Baro, PME';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;   
    case 'Set27' % Set27: 2000 atoms, Prequilibration, v-rescale/PR, tau_t = 0.2 ps, Testing tau_p = 5 ps
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 5.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 5 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set28' % Set28: 2000 atoms, Prequilibration, v-rescale/PR, tau_t = 0.2 ps, Testing tau_p = 2 ps
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 2.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 2 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;        
    case 'Set29' % Set29: 2000 atoms, Prequilibration, v-rescale/PR, tau_t = 0.2 ps, Testing tau_p = 1 ps
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set30' % Set30: 2000 atoms, Prequilibration, v-rescale/PR, tau_t = 0.2 ps, Testing tau_p = 0.5 ps
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 0.5$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 0.5 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set31' % Set31: 2000 atoms, Prequilibration, v-rescale/PR, tau_t = 0.2 ps, Testing tau_p = 0.1 ps
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 0.1$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 0.1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set32' % Set32: 2000 atoms, Prequilibration, v-rescale/PR, tau_p = 1 ps, Testing tau_t = 10 ps
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 10$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 10 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set33' % Set33: 2000 atoms, Prequilibration, v-rescale/PR, tau_p = 1 ps, Testing tau_t = 5 ps
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 5$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 5 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set34' % Set34: 2000 atoms, Prequilibration, v-rescale/PR, tau_p = 1 ps, Testing tau_t = 2 ps
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set35' % Set35: 2000 atoms, Prequilibration, v-rescale/PR, tau_p = 1 ps, Testing tau_t = 1 ps
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 1$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 1 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set36' % Set36: 2000 atoms, Prequilibration, v-rescale/PR, tau_p = 1 ps, Testing tau_t = 0.1 ps
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.1$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.1 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
	case 'Set37' % Set37: 2000 atoms, Prequilibration, v-rescale/PR, tau_p = 1 ps, Testing tau_t = 0.01 ps
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.01$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.01 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
	case 'Set38' % Set38: 2000 atoms, Prequilibration, v-rescale/PR, tau_p = 1 ps, Testing tau_t = 0.001 ps
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.001$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.001 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set39' % Set39: 2000 atoms, Prequilibration, nose-hoover/PR, tau_p = 1 ps, Testing tau_t = 10 ps
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 10$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 10 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set40' % Set40: 2000 atoms, Prequilibration, nose-hoover/PR, tau_p = 1 ps, Testing tau_t = 5 ps
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 5$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 5 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set41' % Set41: 2000 atoms, Prequilibration, nose-hoover/PR, tau_p = 1 ps, Testing tau_t = 2 ps
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set42' % Set42: 2000 atoms, Prequilibration, nose-hoover/PR, tau_p = 1 ps, Testing tau_t = 1 ps
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 1$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 1 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set43' % Set43: 2000 atoms, Prequilibration, nose-hoover/PR, tau_p = 1 ps, Testing tau_t = 0.1 ps
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.1$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.1 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
	case 'Set44' % Set44: 2000 atoms, Prequilibration, nose-hoover/PR, tau_p = 1 ps, Testing tau_t = 0.01 ps
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.01$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.01 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
	case 'Set45' % Set45: 2000 atoms, Prequilibration, nose-hoover/PR, tau_p = 1 ps, Testing tau_t = 0.001 ps
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.001$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.001 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set46' % Set46: 2000 atoms, Prequilibration, nose-hoover/PR, tau_t = 1.0, Testing tau_p = 5 ps
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 1$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 5.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 1 ps$, PR Baro, $\tau_P = 5 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set47' % Set47: 2000 atoms, Prequilibration, nose-hoover/PR, tau_t = 1.0, Testing tau_p = 2 ps
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 1$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 2.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 1 ps$, PR Baro, $\tau_P = 2 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set48' % Set48: 2000 atoms, Prequilibration, nose-hoover/PR, tau_t = 1.0, Testing tau_p = 1 ps
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 1$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1.0$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 1 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
    case 'Set49' % Set49: 2000 atoms, Prequilibration, nose-hoover/PR, tau_t = 1.0, Testing tau_p = 0.5 ps
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 1$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 0.5$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 1 ps$, PR Baro, $\tau_P = 0.5 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
	case 'Set50' % Set50: 2000 atoms, Prequilibration, nose-hoover/PR, tau_t = 1.0, Testing tau_p = 0.1 ps
        Parameters.Thermostat = 'Nose-Hoover Thermostat';
        Parameters.Tau_T = '$\tau_T = 1$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 0.1$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 1 ps$, PR Baro, $\tau_P = 0.1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;       
	case 'Set51' % Set51: Testing Pre-Equilibration + Initial equilibration with my "default" parameters
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6.0,6.0,10.0) nm';
        Parameters.XY = '(x,y) = (6.0,6.0) nm';
        Parameters.Z = 'z = 10.0 nm';
        Parameters.N = 'N = 11618';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 11618, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10; 
	case 'Set52' % Set52: 2000 atoms default settings
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
	case 'Set53' % Set53: 2000 atoms default settings, except removal of dispersion correction
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$, Disp. Corr. OFF';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
	case 'Set54' % Set54: 2000 atoms default settings, except decreasing Ewald_rtol and Fourier_Spacing
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = 'N = 2000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.10 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-7}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 2000, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;  
	case 'Set55' % Set55: Testing Pre-Equilibration + Initial equilibration with my "default" parameters + dispersion correct added
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6.0,6.0,10.0) nm';
        Parameters.XY = '(x,y) = (6.0,6.0) nm';
        Parameters.Z = 'z = 10.0 nm';
        Parameters.N = 'N = 11618';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 11618, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10; 
	case 'Set56' % Set56: Testing Pre-Equilibration + Initial equilibration with my "default" parameters + Rc = 1.4 + dispersion correction off
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6.0,6.0,10.0) nm';
        Parameters.XY = '(x,y) = (6.0,6.0) nm';
        Parameters.Z = 'z = 10.0 nm';
        Parameters.N = 'N = 11618';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 11618, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10; 
	case 'Set57' % Set57: Testing Pre-Equilibration + Initial equilibration with my "default" parameters + Rc = 1.4 + dispersion correction ON
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6.0,6.0,10.0) nm';
        Parameters.XY = '(x,y) = (6.0,6.0) nm';
        Parameters.Z = 'z = 10.0 nm';
        Parameters.N = 'N = 11618';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 11618, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10; 
	case 'Set58' % Set58: Testing Pre-Equilibration + Initial equilibration with my "default" parameters + decreasing Ewald_rtol and Fourier_Spacing
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. OFF';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6.0,6.0,10.0) nm';
        Parameters.XY = '(x,y) = (6.0,6.0) nm';
        Parameters.Z = 'z = 10.0 nm';
        Parameters.N = 'N = 11618';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.10 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-7}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 11618, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10; 
	case 'Set59' % Set59: Testing Pre-Equilibration + Initial equilibration with my "default" parameters + decreasing Ewald_rtol and Fourier_Spacing
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.90$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6.0,6.0,10.0) nm';
        Parameters.XY = '(x,y) = (6.0,6.0) nm';
        Parameters.Z = 'z = 10.0 nm';
        Parameters.N = 'N = 20000';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 20000, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10; 
	case 'Set60' % Set60: Testing Pre-Equilibration + Initial equilibration with my "default" parameters + Rc = 1.4 + dispersion correction ON
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (3.0,3.0,6.0) nm';
        Parameters.XY = '(x,y) = (3.0,3.0) nm';
        Parameters.Z = 'z = 6.0 nm';
        Parameters.N = '$N = 2000$';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '$N = 2000$, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10; 
	case 'Set61' % Set61: Testing Pre-Equilibration + Initial equilibration with my "default" parameters + Rc = 1.4 + dispersion correction ON
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6.0,6.0,12.0) nm';
        Parameters.XY = '(x,y) = (6.0,6.0) nm';
        Parameters.Z = 'z = 12.0 nm';
        Parameters.N = '$N = 11664$';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '$N = 11664$, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;
	case 'Set62'
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 1$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 25 \%';
        Parameters.XYZ = '(x,y,z) = (6.0,6.0,12.0) nm';
        Parameters.XY = '(x,y) = (6.0,6.0) nm';
        Parameters.Z = 'z = 12.0 nm';
        Parameters.N = '$N = 11664$';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = '$N = 11664$, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10; 
	case 'Set63' % Set63: Testing Pre-Equilibration + Initial equilibration with my "default" parameters + Rc = 1.4 + dispersion correction ON
        Parameters.Thermostat = 'V-Rescale Thermostat';
        Parameters.Tau_T = '$\tau_T = 0.2$ ps';
        Parameters.Barostat = 'Parrinello-Rahman Barostat';
        Parameters.Tau_P = '$\tau_P = 1$ ps';
        Parameters.R_C = '$r_{c} = 1.40$ nm';
        Parameters.DispCorr = 'Disp. Corr. ON';
        Parameters.MaxTime = '$t_{max} = 5$ ns';
        Parameters.MeltFreezeThreshold = '$\Delta x_{\mathrm{liquid}}$ = 15 \%';
        Parameters.XYZ = '(x,y,z) = (6.0,6.0,12.0) nm';
        Parameters.XY = '(x,y) = (6.0,6.0) nm';
        Parameters.Z = 'z = 12.0 nm';
        Parameters.N = '$N = 11664$';
        Parameters.Ewald = 'PME Summation';
        Parameters.Fourier_Spacing = 'Fourier Spacing = 0.12 nm';
        Parameters.Ewald_rtol = 'Ewald Rel. Tol. = $10^{-5}$';
        Parameters.PreEquilibrate = 'Pre-Equilibration ON';
        
        Models = {'JC'};
        Dependent_var = 'Rep';
        Legend_txt = 'N = 11664, VR Thermo, $\tau_T = 0.2 ps$, PR Baro, $\tau_P = 1 ps$';
        x_label = 'Trial Number';
        xlimits = [0 11];
        x_ticks = 1:10;

end